# NOTE: This docker container is built automatically
#       from Travis-CI after passing unit tests

FROM python:3

COPY . /code
WORKDIR /code

RUN apt update
RUN apt install -y build-essential libssl-dev libffi-dev python-dev

RUN pip3 install --upgrade pip
RUN pip3 install --requirement requirements.txt

CMD [ "rq", "worker", "--config", "rq_settings", "--name", "tX_Dev_HTML_Job_Handler" ]

# Define environment variables
# NOTE: The following environment variables are optional:
#	REDIS_URL (can be omitted for testing to use a local instance)
#	DEBUG_MODE (can be set to any non-blank string to run in debug mode for testing)
#	GRAPHITE_HOSTNAME (defaults to localhost if missing)
#	QUEUE_PREFIX (defaults to '', set to dev- for testing)


# NOTE: To build use:
#           docker build --file Dockerfile-developBranch --tag unfoldingword/tx_job_handler:develop .


#       To test (assuming that the confidential environment variables are already set in the current environment) use:
#           docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env QUEUE_PREFIX=dev- --env DEBUG_MODE=True --net="host" --name tx_job_handler --rm tx_job_handler:develop


#       To run in production use with the desired values:
#           docker run --env AWS_ACCESS_KEY_ID=<access_key> --env AWS_SECRET_ACCESS_KEY=<sa_key> --env GRAPHITE_HOSTNAME=<graphite_hostname> --env REDIS_URL=<redis_url> --net="host" --name tx_job_handler --detach --rm tx_job_handler:develop
